### ISSUE TITLE
secureHTML Breaking the Template 

### ISSUE THREAD

**Issue by ramenknight** [marcocesarato/PHP-AIO-Security#5]
Hi Marco,

It seems that the function "static function secureHTML" is breaking my template.

I think the code `$doc->loadHTML($buffer);` is responsible for the issue since everything seems to work until that that line...

Any idea why is happening and how I can fix it without just disabling the function?

**Comment by marcocesarato** [comment]
Yes this is possible if the DOMDocument isn't perfectly conform because it is parsed into a DOMDocument object like:

```
$dom = new DOMDocument();
$dom->loadHTML("<html></html>");
```

I can only create a parameter that disable it or you can just not use method `output`.
Disabling it for example auto CSRF will not work but you can use it manually on every single form (like on all other anti-CRSF libs).

My suggestions is to try understand what is wrong for DOMDocument for example with libxml_get_last_error() function.

If you post the wrong code (omit some important fields if you need it) i can try check.

**Comment by ramenknight** [comment]
After further investigation, I found that secureHTML is removing all `</nav>` from the html making the template break...

`</nav>` is from the Bootstrap framework for the navigation menu.

Any idea how this can be fixed?

**Comment by marcocesarato** [comment]
I've created this example: `https://github.com/marcocesarato/PHP-AIO-Security/blob/master/tests/securehtml_test.php` and nav is working good then the problem is probably another.
Which php version are you using?

**Comment by ramenknight** [comment]
True, the example Nav bar works fine... 

I will rebuild my Navigation bar, with a more clean code. Thanks for the support Marco.
